#include "DynamicFeatureFilter.h"
#include "YoloDetector.h"
#include <opencv2/calib3d.hpp>
#include <algorithm>
#include <cmath>

namespace ORB_SLAM3 {
DynamicFeatureFilter::DynamicFeatureFilter(const Config &c) : mConfig(c),mbEngineReady(false),mbStopWorker(false),mbPendingImage(false) {}
DynamicFeatureFilter::~DynamicFeatureFilter(){ {std::lock_guard<std::mutex> l(mMutex);mbStopWorker=true;}mCondition.notify_all();if(mWorker.joinable())mWorker.join(); }
void DynamicFeatureFilter::Configure(const Config &c){mConfig=c;}
bool DynamicFeatureFilter::LoadTensorRTEngine(const std::string &path){if(!mConfig.enabled||mWorker.joinable())return false;mpYoloDetector.reset(new YoloDetector());mbEngineReady=mpYoloDetector->LoadEngine(path);mEnginePath=path;if(mbEngineReady)mWorker=std::thread(&DynamicFeatureFilter::WorkerLoop,this);return mbEngineReady;}
bool DynamicFeatureFilter::IsReady()const{return mbEngineReady&&mpYoloDetector&&mpYoloDetector->IsReady();}
void DynamicFeatureFilter::SubmitImage(const cv::Mat &im)const{if(!mbEngineReady||im.empty())return;{std::lock_guard<std::mutex>l(mMutex);mPendingImage=im.clone();mbPendingImage=true;}mCondition.notify_one();}
bool DynamicFeatureFilter::GetLatestDetections(const cv::Size &size,cv::Mat &mask,std::vector<YoloBoundingBox> &boxes)const{std::lock_guard<std::mutex>l(mMutex);if(mLatestMask.empty()||mLatestMask.size()!=size)return false;mask=mLatestMask.clone();boxes=mLatestBoxes;return true;}
void DynamicFeatureFilter::WorkerLoop(){while(true){cv::Mat im;{std::unique_lock<std::mutex>l(mMutex);mCondition.wait(l,[this]{return mbStopWorker||mbPendingImage;});if(mbStopWorker)return;im=mPendingImage;mbPendingImage=false;}cv::Mat mask;std::vector<YoloBoundingBox> boxes;if(InferDynamicMask(im,mask,boxes)){std::lock_guard<std::mutex>l(mMutex);mLatestMask=mask;mLatestBoxes=boxes;}}}
bool DynamicFeatureFilter::InferDynamicMask(const cv::Mat &im,cv::Mat &mask,std::vector<YoloBoundingBox> &boxes)const{if(!mpYoloDetector||im.empty())return false;if(!mpYoloDetector->Detect(im,boxes))return false;mask=cv::Mat::zeros(im.size(),CV_8U);for(size_t i=0;i<boxes.size();++i)if(YoloDetector::IsDynamicClass(boxes[i].classId)){cv::Rect r=cv::Rect(cvRound(boxes[i].rect.x),cvRound(boxes[i].rect.y),cvRound(boxes[i].rect.width),cvRound(boxes[i].rect.height))&cv::Rect(0,0,im.cols,im.rows);if(r.area()>0)mask(r).setTo(255);}return true;}
void DynamicFeatureFilter::ApplyManhattanImmunity(const cv::Mat&depth,const std::vector<cv::KeyPoint>&keys,std::vector<float>&p,std::vector<unsigned char>&immune)const{if(depth.empty()||depth.type()!=CV_32F)return;cv::Mat valid=depth>0.f;std::vector<cv::Point3f>cloud;for(size_t i=0;i<keys.size();++i){int x=cvRound(keys[i].pt.x),y=cvRound(keys[i].pt.y);if(x>=0&&y>=0&&x<depth.cols&&y<depth.rows&&valid.at<unsigned char>(y,x))cloud.push_back(cv::Point3f((float)x,(float)y,depth.at<float>(y,x)));}if(cloud.size()<30)return;cv::Mat s((int)cloud.size(),3,CV_32F);for(size_t i=0;i<cloud.size();++i){s.at<float>((int)i,0)=cloud[i].x;s.at<float>((int)i,1)=cloud[i].y;s.at<float>((int)i,2)=cloud[i].z;}cv::PCA q(s,cv::Mat(),cv::PCA::DATA_AS_ROW);cv::Vec3f n(q.eigenvectors.at<float>(2,0),q.eigenvectors.at<float>(2,1),q.eigenvectors.at<float>(2,2)),c(q.mean.at<float>(0,0),q.mean.at<float>(0,1),q.mean.at<float>(0,2));float norm=std::sqrt(n.dot(n));if(norm<1e-6f)return;for(size_t i=0;i<keys.size();++i){int x=cvRound(keys[i].pt.x),y=cvRound(keys[i].pt.y);if(x<0||y<0||x>=depth.cols||y>=depth.rows||!valid.at<unsigned char>(y,x))continue;cv::Vec3f pt((float)x,(float)y,depth.at<float>(y,x));if(std::fabs(n.dot(pt-c))/norm<mConfig.planeDistance){p[i]=0.f;immune[i]=1;}}}
void DynamicFeatureFilter::Evaluate(const cv::Mat&mask,const cv::Mat&depth,const std::vector<cv::KeyPoint>&keys,const std::vector<cv::KeyPoint>*prev,std::vector<float>&p,std::vector<unsigned char>&immune)const{p.assign(keys.size(),0.f);immune.assign(keys.size(),0);if(!mask.empty())for(size_t i=0;i<keys.size();++i){int x=cvRound(keys[i].pt.x),y=cvRound(keys[i].pt.y);if(x>=0&&y>=0&&x<mask.cols&&y<mask.rows&&mask.at<unsigned char>(y,x))p[i]=mConfig.dynamicThreshold;}if(prev&&prev->size()==keys.size()&&keys.size()>=8){std::vector<cv::Point2f>a,b;for(size_t i=0;i<keys.size();++i){a.push_back((*prev)[i].pt);b.push_back(keys[i].pt);}cv::Mat F=cv::findFundamentalMat(a,b,cv::FM_RANSAC,1.,.99);if(!F.empty())for(size_t i=0;i<keys.size();++i){cv::Mat x1=(cv::Mat_<double>(3,1)<<a[i].x,a[i].y,1.),x2=(cv::Mat_<double>(3,1)<<b[i].x,b[i].y,1.),Fx=F*x1,Ft=F.t()*x2;double e=x2.dot(Fx),d=Fx.at<double>(0)*Fx.at<double>(0)+Fx.at<double>(1)*Fx.at<double>(1)+Ft.at<double>(0)*Ft.at<double>(0)+Ft.at<double>(1)*Ft.at<double>(1);if(d>1e-12)p[i]=std::max(p[i],(float)(1.-std::exp(-(e*e/d)/(mConfig.sampsonScale*mConfig.sampsonScale))));}}ApplyManhattanImmunity(depth,keys,p,immune);}
}
